resources:
  jobs:
    model_deployment:
      name: model-deployment-workflow
      tags:
        project_name: "credit-risk"

      environments:
        - environment_key: default
          spec:
            environment_version: "3"
            dependencies:
              - ../dist/*.whl

      tasks:
        - task_key: "train_model"
          environment_key: default
          spark_python_task:
            python_file: "../scripts/train_register_custom_model.py"
            parameters:
              - "--root_path"
              - "${workspace.root_path}"
              - "--env"
              - "${bundle.target}"
              - "--git_sha"
              - "${var.git_sha}"
              - "--job_run_id"
              - "{{job.run_id}}"
              - "--branch"
              - "${var.branch}"

        - task_key: model_updated
          condition_task:
            op: "EQUAL_TO"
            left: "{{tasks.train_model.values.model_updated}}"
            right: "1"
          depends_on:
            - task_key: "train_model"

        - task_key: "deploy_model"
          environment_key: default
          depends_on:
            - task_key: "model_updated"
              outcome: "true"
          spark_python_task:
            python_file: "../scripts/deploy_model.py"
            parameters:
              - "--root_path"
              - "${workspace.root_path}"
              - "--env"
              - "${bundle.target}"